config/routes.rb
Rails.application.routes.draw do

  get '/apps/:access_token/chats/count', to: 'apps#get_chat_counts'
  get '/rooms/:app_token/chats/:chat_number/messages/count', to: 'rooms#get_chat_counts'
  get '/messages/:app_token/chats/:chat_number/display', to: 'room_messages#get_messages_under_specif_chat'
  delete '/rooms/:app_token/chats/:chat_number/messages/count', to: 'rooms#delete_room'
  delete '/apps/:access_token/delete', to: 'apps#delete_app'
  delete '/message/:id/delete', to: 'room_messages#delete' 
  post 'rooms/create', to: 'rooms#create'
  resources :apps
  devise_for :users,
             controllers: {
               sessions: 'sessions',
               registrations: 'registrations'
             }

  root controller: :apps, action: :index
  
  resources :room_messages
  resources :room_search_messages
  resources :rooms
  resources :applicationchats
  resources :apps
  
end

app/models/applicationchat.rb
class Applicationchat < ApplicationRecord
end

app/helpers/application_chat_helper.rb
module ApplicationChatHelper
end

app/views/applicationchats/_form.html.erb
<%= simple_form_for @application do |form| %>    
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/applicationchats/index.html.erb
<h1>New Application</h1>
<%= form_with scope: :application_chat, url: applicationchat_path(1) ,local: true do |form| %>
  <p>
    <%= form.label :new_application %><br>
    <%= form.text_field :new_application %>
  </p>
 
  <p>
    <%= form.submit :create %>
  </p>
<% end %>
  

app/views/applicationchats/new.html.erb
<h1>
  Creating a room  
</h1>

<%= render partial: 'form' %>