config/routes.rb
Rails.application.routes.draw do

  get '/apps/:access_token/chats/count', to: 'apps#get_chat_counts'
  get '/rooms/:app_token/chats/:chat_number/messages/count', to: 'rooms#get_chat_counts'
  get '/messages/:app_token/chats/:chat_number/display', to: 'room_messages#get_messages_under_specif_chat'
  delete '/rooms/:app_token/chats/:chat_number/messages/count', to: 'rooms#delete_room'
  delete '/apps/:access_token/delete', to: 'apps#delete_app'
  delete '/message/:id/delete', to: 'room_messages#delete' 
  post 'rooms/create', to: 'rooms#create'
  resources :apps
  devise_for :users,
             controllers: {
               sessions: 'sessions',
               registrations: 'registrations'
             }

  root controller: :apps, action: :index
  
  resources :room_messages
  resources :room_search_messages
  resources :rooms
  resources :applicationchats
  resources :apps
  
end

app/views/apps/_chats.html.erb
<h3 class="text-muted mb-0">
  Chats
</h3>

<hr class="mt-1">
    
  <nav class="nav flex-column">
        <%= simple_form_for @app, :method => :get do |form| %>
          <p>
            <%= text_field_tag :chatsearch, params[:chatsearch] %>
            <%= submit_tag "Search", :name => nil %>
        </p>         
     <% end %>
  </nav>
  
<div class="mt-3">

  <%= simple_form_for @app, :url => new_room_path, :method => :get do |form| %>
      <%= form.input :id , as: :hidden %>
      <%= form.submit "Create a chat", class: 'btn btn-success' %>
  <% end %>



</div>

app/views/apps/_form.html.erb
<%= simple_form_for @app do |form| %>
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>
  

app/views/apps/_rooms.html.erb
<h3 class="text-muted mb-0">
  Applications
</h3>

<hr class="mt-1">
    
  <nav class="nav flex-column">
        <%= simple_form_for @app, :method => :get do |form| %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
        </p>         
     <% end %>
  </nav>
  
<div class="mt-3">
  <%= link_to new_app_path, class: 'btn btn-primary' do %>
    Create a application
  <% end %>
</div>

      
     

app/views/apps/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/apps/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>
    
  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Do you have application token ?!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />
      <p>
        
        You can create or join a application from the sidebar.
      </p>
    </div>
  </div>
</div>
  <% if @apps.present?  %>
       <h1> Your last application token keep it with you to search for application <hr /> Token :  <%= @apps.last.access_token %> <%= %> </ h1>
  <% end %>   
    
  <% if @current_application.present?  %>
      <%= link_to @current_application.last.name, app_path(@current_application.last), class: 'nav-link room-nav-link' %>
 <% end %>       

app/views/apps/new.html.erb
<h1>
  Creating a application 
</h1>

<%= render partial: 'form' %>

app/views/apps/show.html.erb
<h1>
   Application Name:  <%= @app.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'chats' %>
  </div>
</div>

<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="avatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text">

          </p>

          <div class="text-right">
            <small data-role="message-date">
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
    
    
 <% if @current_chats.present?  %>
      <%= link_to @current_chats.last.name, room_path(@current_chats.last), class: 'nav-link room-nav-link' %>
 <% end %>       

    
    